---
- hosts: nodos
  become: yes
  tasks:
     - name: incluir variables
       include_vars:  varspaquetes.yml     
     - name: incluir play
       include_tasks:  playinclusiones1.yml
       vars:
          paquete: "{{ paquetes.fpkg }}"
...
